import React from 'react';
import { Helmet } from 'react-helmet';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Layout } from '@/components/common/layout';
import { Separator } from '@/components/ui/separator';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { CheckCircle2, Copy, FileText, Info, Key, Lock, Shield, Ticket } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';

export default function ApiDocumentation() {
  const { toast } = useToast();
  
  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied to clipboard",
      description: "The code snippet has been copied to your clipboard.",
      duration: 2000,
    });
  };

  return (
    <Layout>
      <Helmet>
        <title>API Documentation | Ticket Management System</title>
      </Helmet>
      
      <div className="container mx-auto py-6 max-w-7xl">
        <h1 className="text-3xl font-bold mb-4">External API Documentation</h1>
        <p className="text-gray-600 mb-6">
          The Ticket Management System provides a set of secure APIs for event managers to integrate with external systems.
        </p>

        <Alert className="mb-6">
          <Info className="h-4 w-4" />
          <AlertTitle>Important</AlertTitle>
          <AlertDescription>
            These APIs require authentication using API keys. Contact the system administrator to obtain your API key.
          </AlertDescription>
        </Alert>

        <Tabs defaultValue="authentication" className="mb-8">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="authentication">Authentication</TabsTrigger>
            <TabsTrigger value="tickets">Tickets</TabsTrigger>
            <TabsTrigger value="validation">Validation</TabsTrigger>
            <TabsTrigger value="examples">Code Examples</TabsTrigger>
          </TabsList>

          <TabsContent value="authentication" className="mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Key className="mr-2 h-5 w-5" />
                  API Key Authentication
                </CardTitle>
                <CardDescription>
                  All API requests must include your API key in the request headers.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <h3 className="text-lg font-semibold mb-2">Request Headers</h3>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Header</TableHead>
                      <TableHead>Description</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-mono">x-api-key</TableCell>
                      <TableCell>Your unique API key provided by the system administrator</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>

                <div className="mt-6">
                  <h3 className="text-lg font-semibold mb-2">Example Request</h3>
                  <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm relative">
                    <pre>
{`curl -X GET https://your-app-domain.com/api/external/events/123/tickets \\
  -H "x-api-key: your_api_key_here"`}
                    </pre>
                    <Button 
                      variant="ghost" 
                      size="icon" 
                      className="absolute top-2 right-2"
                      onClick={() => copyToClipboard('curl -X GET https://your-app-domain.com/api/external/events/123/tickets \\\n  -H "x-api-key: your_api_key_here"')}
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </div>

                <div className="mt-6">
                  <h3 className="text-lg font-semibold mb-2">Security Considerations</h3>
                  <ul className="list-disc pl-5 space-y-2">
                    <li>Keep your API key secure and never share it publicly</li>
                    <li>API keys are tied to your event manager account</li>
                    <li>You can only access data for events that you have created</li>
                    <li>API keys can be revoked and regenerated by the system administrator</li>
                  </ul>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="tickets" className="space-y-6 mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Ticket className="mr-2 h-5 w-5" />
                  Get Event Tickets
                </CardTitle>
                <CardDescription>
                  Retrieve all tickets for a specific event.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-2 mb-4">
                  <Badge className="bg-green-600">GET</Badge>
                  <span className="font-mono text-sm">/api/external/events/:eventId/tickets</span>
                </div>

                <h3 className="text-lg font-semibold mb-2">Path Parameters</h3>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Parameter</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Description</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-mono">eventId</TableCell>
                      <TableCell>Number</TableCell>
                      <TableCell>The ID of the event to retrieve tickets for</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>

                <h3 className="text-lg font-semibold mt-6 mb-2">Response</h3>
                <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm relative overflow-auto max-h-80">
                  <pre>
{`{
  "code": 200,
  "success": true,
  "data": [
    {
      "id": 42,
      "eventId": 123,
      "ticketTypeId": 5,
      "userId": 789,
      "purchaseDate": "2023-05-23T14:30:45.000Z",
      "quantity": 1,
      "totalPrice": "25.00",
      "orderId": "ORD-123456",
      "qrCode": "data:image/png;base64,iVBORw0KGgoA...",
      "isUsed": false,
      "eventDate": "2023-06-15T18:00:00.000Z",
      "attendeeDetails": {
        "fullName": "John Doe",
        "email": "john@example.com",
        "phone": "+1234567890"
      }
    },
    // More tickets...
  ],
  "description": "Event tickets retrieved successfully"
}`}
                  </pre>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute top-2 right-2"
                    onClick={() => copyToClipboard('{\n  "code": 200,\n  "success": true,\n  "data": [\n    {\n      "id": 42,\n      "eventId": 123,\n      "ticketTypeId": 5,\n      "userId": 789,\n      "purchaseDate": "2023-05-23T14:30:45.000Z",\n      "quantity": 1,\n      "totalPrice": "25.00",\n      "orderId": "ORD-123456",\n      "qrCode": "data:image/png;base64,iVBORw0KGgoA...",\n      "isUsed": false,\n      "eventDate": "2023-06-15T18:00:00.000Z",\n      "attendeeDetails": {\n        "fullName": "John Doe",\n        "email": "john@example.com",\n        "phone": "+1234567890"\n      }\n    },\n    // More tickets...\n  ],\n  "description": "Event tickets retrieved successfully"\n}')}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Ticket className="mr-2 h-5 w-5" />
                  Get Ticket Details
                </CardTitle>
                <CardDescription>
                  Retrieve details for a specific ticket.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-2 mb-4">
                  <Badge className="bg-green-600">GET</Badge>
                  <span className="font-mono text-sm">/api/external/tickets/:ticketId</span>
                </div>

                <h3 className="text-lg font-semibold mb-2">Path Parameters</h3>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Parameter</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Description</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-mono">ticketId</TableCell>
                      <TableCell>Number</TableCell>
                      <TableCell>The ID of the ticket to retrieve</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>

                <h3 className="text-lg font-semibold mt-6 mb-2">Response</h3>
                <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm relative overflow-auto max-h-80">
                  <pre>
{`{
  "code": 200,
  "success": true,
  "data": {
    "ticket": {
      "id": 42,
      "eventId": 123,
      "ticketTypeId": 5,
      "userId": 789,
      "purchaseDate": "2023-05-23T14:30:45.000Z",
      "quantity": 1,
      "totalPrice": "25.00",
      "orderId": "ORD-123456",
      "qrCode": "data:image/png;base64,iVBORw0KGgoA...",
      "isUsed": false,
      "eventDate": "2023-06-15T18:00:00.000Z",
      "attendeeDetails": {
        "fullName": "John Doe",
        "email": "john@example.com",
        "phone": "+1234567890"
      }
    },
    "event": {
      "id": 123,
      "title": "Summer Concert",
      "description": "Annual summer concert in the park",
      "location": "Central Park",
      "startDate": "2023-06-15T18:00:00.000Z",
      "category": "Music"
    },
    "ticketType": {
      "id": 5,
      "name": "VIP",
      "price": "25.00",
      "description": "VIP access with premium seating"
    }
  },
  "description": "Ticket details retrieved successfully"
}`}
                  </pre>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute top-2 right-2"
                    onClick={() => copyToClipboard('{\n  "code": 200,\n  "success": true,\n  "data": {\n    "ticket": {\n      "id": 42,\n      "eventId": 123,\n      "ticketTypeId": 5,\n      "userId": 789,\n      "purchaseDate": "2023-05-23T14:30:45.000Z",\n      "quantity": 1,\n      "totalPrice": "25.00",\n      "orderId": "ORD-123456",\n      "qrCode": "data:image/png;base64,iVBORw0KGgoA...",\n      "isUsed": false,\n      "eventDate": "2023-06-15T18:00:00.000Z",\n      "attendeeDetails": {\n        "fullName": "John Doe",\n        "email": "john@example.com",\n        "phone": "+1234567890"\n      }\n    },\n    "event": {\n      "id": 123,\n      "title": "Summer Concert",\n      "description": "Annual summer concert in the park",\n      "location": "Central Park",\n      "startDate": "2023-06-15T18:00:00.000Z",\n      "category": "Music"\n    },\n    "ticketType": {\n      "id": 5,\n      "name": "VIP",\n      "price": "25.00",\n      "description": "VIP access with premium seating"\n    }\n  },\n  "description": "Ticket details retrieved successfully"\n}')}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Ticket className="mr-2 h-5 w-5" />
                  Purchase Tickets
                </CardTitle>
                <CardDescription>
                  Purchase tickets for an event.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-2 mb-4">
                  <Badge className="bg-blue-600">POST</Badge>
                  <span className="font-mono text-sm">/api/external/tickets/purchase</span>
                </div>

                <h3 className="text-lg font-semibold mb-2">Request Body</h3>
                <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm relative overflow-auto max-h-80">
                  <pre>
{`{
  "eventId": 123,
  "isMultiDay": false,
  "ticketSelections": [
    {
      "ticketTypeId": 5,
      "quantity": 2,
      "eventDate": "2023-06-15T18:00:00.000Z",
      "attendeeDetails": [
        {
          "fullName": "John Doe",
          "email": "john@example.com",
          "phone": "+1234567890"
        }
      ]
    }
  ],
  "paymentSessionId": "PAYMENT-123456", // Optional
  "purchaseForUserId": 789 // Optional, used to specify which user the tickets are for
}`}
                  </pre>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute top-2 right-2"
                    onClick={() => copyToClipboard('{\n  "eventId": 123,\n  "isMultiDay": false,\n  "ticketSelections": [\n    {\n      "ticketTypeId": 5,\n      "quantity": 2,\n      "eventDate": "2023-06-15T18:00:00.000Z",\n      "attendeeDetails": [\n        {\n          "fullName": "John Doe",\n          "email": "john@example.com",\n          "phone": "+1234567890"\n        }\n      ]\n    }\n  ],\n  "paymentSessionId": "PAYMENT-123456", // Optional\n  "purchaseForUserId": 789 // Optional, used to specify which user the tickets are for\n}')}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>

                <h3 className="text-lg font-semibold mt-6 mb-2">Response</h3>
                <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm relative overflow-auto max-h-80">
                  <pre>
{`{
  "code": 201,
  "success": true,
  "data": [
    {
      "id": 42,
      "eventId": 123,
      "ticketTypeId": 5,
      "userId": 789,
      "purchaseDate": "2023-05-23T14:30:45.000Z",
      "quantity": 1,
      "totalPrice": "25.00",
      "orderId": "ORD-123456",
      "qrCode": "data:image/png;base64,iVBORw0KGgoA...",
      "isUsed": false,
      "eventDate": "2023-06-15T18:00:00.000Z",
      "attendeeDetails": {
        "fullName": "John Doe",
        "email": "john@example.com",
        "phone": "+1234567890"
      }
    },
    // More tickets...
  ],
  "description": "Tickets purchased successfully"
}`}
                  </pre>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute top-2 right-2"
                    onClick={() => copyToClipboard('{\n  "code": 201,\n  "success": true,\n  "data": [\n    {\n      "id": 42,\n      "eventId": 123,\n      "ticketTypeId": 5,\n      "userId": 789,\n      "purchaseDate": "2023-05-23T14:30:45.000Z",\n      "quantity": 1,\n      "totalPrice": "25.00",\n      "orderId": "ORD-123456",\n      "qrCode": "data:image/png;base64,iVBORw0KGgoA...",\n      "isUsed": false,\n      "eventDate": "2023-06-15T18:00:00.000Z",\n      "attendeeDetails": {\n        "fullName": "John Doe",\n        "email": "john@example.com",\n        "phone": "+1234567890"\n      }\n    },\n    // More tickets...\n  ],\n  "description": "Tickets purchased successfully"\n}')}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="validation" className="mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <CheckCircle2 className="mr-2 h-5 w-5" />
                  Validate Ticket (Check-in)
                </CardTitle>
                <CardDescription>
                  Mark a ticket as used (validated) at event check-in.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-2 mb-4">
                  <Badge className="bg-blue-600">POST</Badge>
                  <span className="font-mono text-sm">/api/external/tickets/:ticketId/validate</span>
                </div>

                <h3 className="text-lg font-semibold mb-2">Path Parameters</h3>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Parameter</TableHead>
                      <TableHead>Type</TableHead>
                      <TableHead>Description</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell className="font-mono">ticketId</TableCell>
                      <TableCell>Number</TableCell>
                      <TableCell>The ID of the ticket to validate</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>

                <h3 className="text-lg font-semibold mt-6 mb-2">Request Body</h3>
                <p className="text-gray-600 mb-4">No request body is required for this endpoint.</p>

                <h3 className="text-lg font-semibold mt-6 mb-2">Response</h3>
                <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm relative">
                  <pre>
{`{
  "code": 200,
  "success": true,
  "data": {
    "validated": true
  },
  "description": "Ticket validated successfully"
}`}
                  </pre>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute top-2 right-2"
                    onClick={() => copyToClipboard('{\n  "code": 200,\n  "success": true,\n  "data": {\n    "validated": true\n  },\n  "description": "Ticket validated successfully"\n}')}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>

                <div className="mt-6">
                  <h3 className="text-lg font-semibold mb-2">Error Responses</h3>
                  <Badge className="bg-red-600 mb-2">400 Bad Request</Badge>
                  <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm mb-4 relative">
                    <pre>
{`{
  "code": 400,
  "success": false,
  "description": "Ticket has already been used"
}`}
                    </pre>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="absolute top-2 right-2"
                      onClick={() => copyToClipboard('{\n  "code": 400,\n  "success": false,\n  "description": "Ticket has already been used"\n}')}
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>

                  <Badge className="bg-red-600 mb-2">404 Not Found</Badge>
                  <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm relative">
                    <pre>
{`{
  "code": 404,
  "success": false,
  "description": "Ticket not found"
}`}
                    </pre>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="absolute top-2 right-2"
                      onClick={() => copyToClipboard('{\n  "code": 404,\n  "success": false,\n  "description": "Ticket not found"\n}')}
                    >
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="examples" className="space-y-6 mt-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <FileText className="mr-2 h-5 w-5" />
                  JavaScript / Node.js Example
                </CardTitle>
                <CardDescription>
                  Fetch tickets for an event using the Fetch API.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm relative">
                  <pre>
{`// Fetch event tickets
async function getEventTickets(eventId, apiKey) {
  const response = await fetch(
    \`https://your-app-domain.com/api/external/events/\${eventId}/tickets\`,
    {
      headers: {
        'x-api-key': apiKey,
      },
    }
  );

  if (!response.ok) {
    throw new Error(\`Error: \${response.status}\`);
  }

  const data = await response.json();
  return data.data; // Return the tickets array
}

// Validate a ticket
async function validateTicket(ticketId, apiKey) {
  const response = await fetch(
    \`https://your-app-domain.com/api/external/tickets/\${ticketId}/validate\`,
    {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
      },
    }
  );

  if (!response.ok) {
    throw new Error(\`Error: \${response.status}\`);
  }

  const data = await response.json();
  return data.data.validated;
}

// Purchase tickets
async function purchaseTickets(apiKey, purchaseData) {
  const response = await fetch(
    'https://your-app-domain.com/api/external/tickets/purchase',
    {
      method: 'POST',
      headers: {
        'x-api-key': apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(purchaseData),
    }
  );

  if (!response.ok) {
    throw new Error(\`Error: \${response.status}\`);
  }

  const data = await response.json();
  return data.data; // Return the created tickets
}`}
                  </pre>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute top-2 right-2"
                    onClick={() => copyToClipboard('// Fetch event tickets\nasync function getEventTickets(eventId, apiKey) {\n  const response = await fetch(\n    `https://your-app-domain.com/api/external/events/${eventId}/tickets`,\n    {\n      headers: {\n        \'x-api-key\': apiKey,\n      },\n    }\n  );\n\n  if (!response.ok) {\n    throw new Error(`Error: ${response.status}`);\n  }\n\n  const data = await response.json();\n  return data.data; // Return the tickets array\n}\n\n// Validate a ticket\nasync function validateTicket(ticketId, apiKey) {\n  const response = await fetch(\n    `https://your-app-domain.com/api/external/tickets/${ticketId}/validate`,\n    {\n      method: \'POST\',\n      headers: {\n        \'x-api-key\': apiKey,\n      },\n    }\n  );\n\n  if (!response.ok) {\n    throw new Error(`Error: ${response.status}`);\n  }\n\n  const data = await response.json();\n  return data.data.validated;\n}\n\n// Purchase tickets\nasync function purchaseTickets(apiKey, purchaseData) {\n  const response = await fetch(\n    \'https://your-app-domain.com/api/external/tickets/purchase\',\n    {\n      method: \'POST\',\n      headers: {\n        \'x-api-key\': apiKey,\n        \'Content-Type\': \'application/json\',\n      },\n      body: JSON.stringify(purchaseData),\n    }\n  );\n\n  if (!response.ok) {\n    throw new Error(`Error: ${response.status}`);\n  }\n\n  const data = await response.json();\n  return data.data; // Return the created tickets\n}')}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <FileText className="mr-2 h-5 w-5" />
                  Python Example
                </CardTitle>
                <CardDescription>
                  Make API requests using the requests library in Python.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="bg-gray-900 text-gray-100 p-4 rounded-md font-mono text-sm relative">
                  <pre>
{`import requests
import json

BASE_URL = "https://your-app-domain.com/api/external"
API_KEY = "your_api_key_here"  # Replace with your actual API key

def get_event_tickets(event_id):
    """Fetch all tickets for an event"""
    url = f"{BASE_URL}/events/{event_id}/tickets"
    headers = {"x-api-key": API_KEY}
    
    response = requests.get(url, headers=headers)
    response.raise_for_status()  # Raise exception for 4XX/5XX responses
    
    data = response.json()
    return data["data"]

def validate_ticket(ticket_id):
    """Validate a ticket (check-in)"""
    url = f"{BASE_URL}/tickets/{ticket_id}/validate"
    headers = {"x-api-key": API_KEY}
    
    response = requests.post(url, headers=headers)
    response.raise_for_status()
    
    data = response.json()
    return data["data"]["validated"]

def purchase_tickets(purchase_data):
    """Purchase tickets for an event"""
    url = f"{BASE_URL}/tickets/purchase"
    headers = {
        "x-api-key": API_KEY,
        "Content-Type": "application/json"
    }
    
    response = requests.post(
        url, 
        headers=headers, 
        data=json.dumps(purchase_data)
    )
    response.raise_for_status()
    
    data = response.json()
    return data["data"]

# Example usage
if __name__ == "__main__":
    # Get tickets for event with ID 123
    tickets = get_event_tickets(123)
    print(f"Found {len(tickets)} tickets")
    
    # Validate a ticket
    if tickets:
        ticket_id = tickets[0]["id"]
        validated = validate_ticket(ticket_id)
        print(f"Ticket {ticket_id} validated: {validated}")
    
    # Purchase tickets
    purchase_data = {
        "eventId": 123,
        "isMultiDay": False,
        "ticketSelections": [
            {
                "ticketTypeId": 5,
                "quantity": 2,
                "attendeeDetails": [
                    {
                        "fullName": "Jane Doe",
                        "email": "jane@example.com",
                        "phone": "+1234567890"
                    }
                ]
            }
        ]
    }
    
    new_tickets = purchase_tickets(purchase_data)
    print(f"Purchased {len(new_tickets)} new tickets")`}
                  </pre>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute top-2 right-2"
                    onClick={() => copyToClipboard('import requests\nimport json\n\nBASE_URL = "https://your-app-domain.com/api/external"\nAPI_KEY = "your_api_key_here"  # Replace with your actual API key\n\ndef get_event_tickets(event_id):\n    """Fetch all tickets for an event"""\n    url = f"{BASE_URL}/events/{event_id}/tickets"\n    headers = {"x-api-key": API_KEY}\n    \n    response = requests.get(url, headers=headers)\n    response.raise_for_status()  # Raise exception for 4XX/5XX responses\n    \n    data = response.json()\n    return data["data"]\n\ndef validate_ticket(ticket_id):\n    """Validate a ticket (check-in)"""\n    url = f"{BASE_URL}/tickets/{ticket_id}/validate"\n    headers = {"x-api-key": API_KEY}\n    \n    response = requests.post(url, headers=headers)\n    response.raise_for_status()\n    \n    data = response.json()\n    return data["data"]["validated"]\n\ndef purchase_tickets(purchase_data):\n    """Purchase tickets for an event"""\n    url = f"{BASE_URL}/tickets/purchase"\n    headers = {\n        "x-api-key": API_KEY,\n        "Content-Type": "application/json"\n    }\n    \n    response = requests.post(\n        url, \n        headers=headers, \n        data=json.dumps(purchase_data)\n    )\n    response.raise_for_status()\n    \n    data = response.json()\n    return data["data"]\n\n# Example usage\nif __name__ == "__main__":\n    # Get tickets for event with ID 123\n    tickets = get_event_tickets(123)\n    print(f"Found {len(tickets)} tickets")\n    \n    # Validate a ticket\n    if tickets:\n        ticket_id = tickets[0]["id"]\n        validated = validate_ticket(ticket_id)\n        print(f"Ticket {ticket_id} validated: {validated}")\n    \n    # Purchase tickets\n    purchase_data = {\n        "eventId": 123,\n        "isMultiDay": False,\n        "ticketSelections": [\n            {\n                "ticketTypeId": 5,\n                "quantity": 2,\n                "attendeeDetails": [\n                    {\n                        "fullName": "Jane Doe",\n                        "email": "jane@example.com",\n                        "phone": "+1234567890"\n                    }\n                ]\n            }\n        ]\n    }\n    \n    new_tickets = purchase_tickets(purchase_data)\n    print(f"Purchased {len(new_tickets)} new tickets")')}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>

        <Separator className="my-8" />

        <div className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Getting Started</h2>
          <ol className="list-decimal pl-5 space-y-3">
            <li>
              <strong>Obtain an API Key:</strong> Contact your system administrator to request an API key for the external API.
            </li>
            <li>
              <strong>Integrate with Your Application:</strong> Use the code examples and API documentation to implement the integration in your application.
            </li>
            <li>
              <strong>Test Your Integration:</strong> Test your integration thoroughly with a few sample requests before going live.
            </li>
            <li>
              <strong>Monitor Usage:</strong> Keep track of your API usage and ensure it aligns with your business requirements.
            </li>
          </ol>
        </div>

        <Alert className="mb-8">
          <Shield className="h-4 w-4" />
          <AlertTitle>Rate Limiting</AlertTitle>
          <AlertDescription>
            API requests are rate-limited to prevent abuse. If you encounter rate-limiting issues, consider optimizing your requests or contact the administrator for increased limits.
          </AlertDescription>
        </Alert>

        <div className="border-t pt-6">
          <h2 className="text-2xl font-bold mb-4">Support</h2>
          <p className="text-gray-600">
            If you have any questions or need assistance with the API, please contact our support team at <a href="mailto:support@example.com" className="text-primary hover:underline">support@example.com</a>.
          </p>
        </div>
      </div>
    </Layout>
  );
}